# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-08-30 07:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cake_baby', '0003_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='photo_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
